package ui

import (
	"log"

	"github.com/LaPingvino/goloco/pkg/gfx"
)

// Auto-generated by batch_ai_impl using opencode + GPT-5-mini
// Original: Ui/WindowManager.cpp

// Global window management state
var (
	windows         []*Window
	focusedWindow   *Window
	modalWindow     *Window
	updateViewports func()
)

// Type aliases for compatibility
type Rect = gfx.Rect
type Size = gfx.Size
type Point = gfx.Point

// Constants
const (
	kWidgetIndexNull          = WidgetIndex(-1)
	WindowTypeUndefined       = WindowType(255)
	WindowFlagsIgnoreInFindAt = WindowFlagNoAutoClose
	WindowFlagsStickToBack    = WindowFlagStickToBack
	WindowFlagsStickToFront   = WindowFlagStickToFront
)

// WindowEventList placeholder
type WindowEventList struct{}

// Helper functions needed by AI-generated code
func (w *Window) HasFlags(flags WindowFlags) bool {
	return w.Flags&flags != 0
}

// ProcessEvents is a stub. Not yet implemented.
//
// OpenLoco reference: src/OpenLoco/src/Ui/WindowManager.cpp
//
//	WindowManager::update() — iterates windows and dispatches input events
//
// Also: src/OpenLoco/src/Ui/Window.cpp
//
//	Window::callUpdate()
//
// In OpenLoco, per-window event processing is driven by the WindowEventTable
// registered for each window type.  Input (mouse/keyboard) is routed through
// WindowManager::processEvent() before reaching individual windows.
func (w *Window) ProcessEvents() error {
	log.Println("[UI] Window.ProcessEvents: stub — not yet implemented")
	return nil
}

// UpdateAnimations is a stub. Not yet implemented.
//
// OpenLoco reference: src/OpenLoco/src/Ui/WindowManager.cpp
//
//	WindowManager::update() — advances animation state per frame
//
// Also: src/OpenLoco/src/Ui/Window.cpp
//
//	Window::callPeriodicUpdate()  (fires every 1000 ticks)
//
// In OpenLoco, animation state (e.g. blinking cursors, sprite frame
// sequences) is advanced here based on the thousandthTickCounter.
func (w *Window) UpdateAnimations() error {
	log.Println("[UI] Window.UpdateAnimations: stub — not yet implemented")
	return nil
}

// ViewportsUpdatePosition is a stub. Not yet implemented.
//
// OpenLoco reference: src/OpenLoco/src/Ui/WindowManager.cpp
//
//	WindowManager::updateViewports()
//
// Also: src/OpenLoco/src/Ui/Window.cpp
//
//	Window::viewportsUpdatePosition()
//
// In OpenLoco this keeps each viewport's world-space origin in sync with
// its parent window position and the current scroll/zoom state.
func (w *Window) ViewportsUpdatePosition() error {
	log.Println("[UI] Window.ViewportsUpdatePosition: stub — not yet implemented")
	return nil
}

func (w *Window) CallOnResize() error {
	if w.OnResize != nil {
		w.OnResize(w, w.Width, w.Height)
	}
	return nil
}

func (w *Window) Invalidate() {
	if w == nil {
		return
	}
	w.Invalidated = true

	for _, vp := range w.viewports {
		if vp != nil {
			vp.Invalidated = true
		}
	}

	for _, child := range w.children {
		if child != nil {
			child.Invalidated = true
		}
	}

	if w.owner != nil {
		w.owner.Invalidated = true
	}
}

func (w *Window) IsHidden() bool {
	return !w.Visible
}

func WindowManagerCount() int {
	return len(windows)
}

func WindowManagerGet(index int) *Window {
	if index < 0 || index >= len(windows) {
		return nil
	}
	return windows[index]
}

// UiWidth returns the current UI screen width. Stub — hardcoded to 800.
//
// OpenLoco reference: src/OpenLoco/src/Ui.h
//
//	Ui::width()  — reads from Ui::ScreenInfo::width
//
// Wire this to the actual Ebiten window width once a shared screen-size
// struct (or a simple global set at window creation) is in place.
func UiWidth() int16 {
	log.Println("[UI] UiWidth: stub — returning hardcoded 800")
	return 800
}

// UiHeight returns the current UI screen height. Stub — hardcoded to 600.
//
// OpenLoco reference: src/OpenLoco/src/Ui.h
//
//	Ui::height()  — reads from Ui::ScreenInfo::height
func UiHeight() int16 {
	log.Println("[UI] UiHeight: stub — returning hardcoded 600")
	return 600
}

// GfxRender is a stub. Not yet implemented.
//
// OpenLoco reference: src/OpenLoco/src/Graphics/Gfx.cpp  (Gfx::render)
// Also: src/OpenLoco/src/Graphics/SoftwareDrawingContext.cpp
//
//	SoftwareDrawingContext::clear(uint32_t fill)
//	SoftwareDrawingContext::clearSingle(uint8_t paletteId)
//
// In OpenLoco, Gfx::render triggers the full back-buffer → screen blit
// for the given dirty rectangle.  The SoftwareDrawingContext handles the
// actual pixel operations.
func GfxRender(left, top, right, bottom int16) {
	log.Printf("[UI] GfxRender: stub — region (%d,%d)-(%d,%d) not yet rendered", left, top, right, bottom)
}

// Update all windows (events, animations)
// Source: WindowManager::update
func UpdateWindows() {
	for _, w := range windows {
		if w == nil {
			continue
		}

		// Process input/events for this window
		_ = w.ProcessEvents()

		// Advance animations / time-based window updates
		_ = w.UpdateAnimations()

		// Keep viewports aligned with the window's position/state
		_ = w.ViewportsUpdatePosition()

		// Call custom update callback
		if w.OnUpdate != nil {
			w.OnUpdate(w)
		}
	}
}

// Find window at screen position
// Source: WindowManager::findAt
func FindWindowAt(x, y int16) *Window {
	for i := len(windows) - 1; i >= 0; i-- {
		w := windows[i]
		if w == nil {
			continue
		}

		// Bounding box check
		if x < w.X || x >= w.X+w.Width {
			continue
		}
		if y < w.Y || y >= w.Y+w.Height {
			continue
		}

		// Skip windows that should be ignored by hit-testing
		if w.HasFlags(WindowFlagsIgnoreInFindAt) {
			continue
		}

		return w
	}
	return nil
}

// Find window by type and number
// Source: WindowManager::find
func FindWindow(typ WindowType, number WindowNumber) *Window {
	// Search top-most windows first so the front-most match is returned.
	for i := len(windows) - 1; i >= 0; i-- {
		w := windows[i]
		if w == nil {
			continue
		}
		// Match by type and number. A sentinel of -1 for `number` means "any number".
		if w.Type == typ && (number == WindowNumber(0xFFFF) || w.Number == number) {
			return w
		}
	}
	return nil
}

// Bring window to front of Z-order
// Source: WindowManager::bringToFront
func BringWindowToFront(window *Window) *Window {
	{
		// nil-check for safety
		if window == nil {
			return nil
		}

		// If window is forced to back/front, don't change z-order.
		if window.HasFlags(WindowFlagsStickToBack | WindowFlagsStickToFront) {
			return window
		}

		// Find the front-most window that is not "stick to back".
		var frontMostWnd *Window
		for i := len(windows); i > 0; i-- {
			w := windows[i-1]
			if !w.HasFlags(WindowFlagsStickToBack) {
				frontMostWnd = w
				break
			}
		}

		result := window
		// If we found a candidate and it's not already the very first or the same window, swap them.
		if frontMostWnd != nil && frontMostWnd != windows[0] && frontMostWnd != window {
			fi, wi := -1, -1
			for i, w := range windows {
				if w == frontMostWnd {
					fi = i
				}
				if w == window {
					wi = i
				}
			}
			if fi != -1 && wi != -1 {
				windows[fi], windows[wi] = windows[wi], windows[fi]
				result = frontMostWnd
				result.Invalidate()
			}
		}

		// If the window is almost off-screen to the left, shift it right.
		right := result.X + result.Width
		if right < 20 {
			shiftRight := 20 - result.X
			result.X = 20
			for _, vp := range result.Viewports {
				if vp != nil {
					vp.X += shiftRight
				}
			}
			result.Invalidate()
		}

		return result
	}
}

// Render all windows to context
// Source: WindowManager::render
func RenderWindows(dc *DrawingContext, rect Rect) {
	// Render all visible windows
	for _, win := range windows {
		if win == nil {
			continue
		}

		// Skip windows without size or not visible
		if win.Width <= 0 || win.Height <= 0 {
			continue
		}
		if win.IsHidden() {
			continue
		}

		// Draw the window
		win.Draw(dc)
	}
}

// Close and destroy window
// Source: WindowManager::close
func CloseWindow(window *Window) {
	{
		// nil check
		if window == nil {
			return
		}

		// Call close callback if present; protect against panics in callbacks
		if cb := window.OnClose; cb != nil {
			func() {
				defer func() {
					_ = recover() // swallow panics from user callbacks to avoid breaking UI loop
				}()
				cb(window)
			}()
		}

		// Close and clear viewports
		if window.Viewports != nil {
			for i := range window.Viewports {
				vp := window.Viewports[i]
				if vp == nil {
					continue
				}
				// If viewport exposes a Close method, call it and ignore returned error
				if closer, ok := interface{}(vp).(interface{ Close() error }); ok {
					_ = closer.Close()
				} else if closerNoErr, ok := interface{}(vp).(interface{ Close() }); ok {
					closerNoErr.Close()
				}
				window.Viewports[i] = nil
			}
			window.Viewports = nil
		}

		// Clear widgets
		window.Widgets = nil

		// Remove from global windows slice if present
		for i, w := range windows {
			if w == window {
				// preserve order
				windows = append(windows[:i], windows[i+1:]...)
				break
			}
		}

		// Clear any global references to this window (focus/modal)
		if focusedWindow == window {
			focusedWindow = nil
		}
		if modalWindow == window {
			modalWindow = nil
		}

		// Mark as destroyed so other code can detect it; attempt a graceful destroy call if present
		if destroyer, ok := interface{}(window).(interface{ Destroy() error }); ok {
			_ = destroyer.Destroy()
		} else if destroyNoErr, ok := interface{}(window).(interface{ Destroy() }); ok {
			destroyNoErr.Destroy()
		} else {
			// best-effort: set a flag that signals this window is closed
			window.Destroyed = true
		}

		// Request a UI update / redraw if helper exists
		if updateViewports != nil {
			updateViewports()
		}
	}
}

// Create new window
// Source: WindowManager::createWindow
func CreateWindow(typ WindowType, x, y, width, height int16, flags WindowFlags) *Window {
	w := &Window{
		Type:    typ,
		X:       x,
		Y:       y,
		Width:   width,
		Height:  height,
		Flags:   flags,
		Widgets: make([]Widget, 0),
		Visible: true,
	}

	windows = append(windows, w)
	return w
}

// Initialize window management system
// Source: WindowManager::init
func InitWindowManager() {
	{
		// Clear the windows list but keep underlying capacity (like C++ clear).
		windows = windows[:0]
	}
}
